# Generated by Django 6.1 on 2026-09-13 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('language', 'Language'), ('software', 'Software & Tools'), ('technical', 'Technical Skill'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
